export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_USERS_REQUEST_SAGA = 'FETCH_USERS_REQUEST_SAGA'
export const FETCH_USERS_SUCCESS_SAGA = 'FETCH_USERS_SUCCESS_SAGA'
export const FETCH_USERS_FAILURE_SAGA = 'FETCH_USERS_FAILURE_SAGA'

